name: Application CI - DEV

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    name: Artist pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Run backend test
        run: |
          chmod +x mvnw
          ./mvnw clean compile
          ./mvnw jib:bulid -Djib.to.image=imkunyoung/a-artist-dev${DOCKER_TAG} -Djib.to.auth.username="${{secrets.DOCKERHUB_USERNAME }}" -Djib.to.auth.password="${{secrets.DOCKERHUB_PASSWORD }}" -Pdev
