# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OWI5NWRhNTVhNmQ4YTE5YmQ0MTEwMTI0MjZlZWMwYzBkNzJkNjg5YzljMzI3OWY5NGM5ZmZjODkxYmIwYjNhNjI1YTQ0MDcxZGQzMDExZGM4MGRlNWI1ZDI2MTc2ZWFhY2EyNDJlNDFiMGE0OGFhYWE3Yzg0YWM1YjdkNThjNTI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
